{{- if .Values.imagePassword }}
apiVersion: v1
kind: Secret
metadata:
  name: acr-auth
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageRegistry (printf "%s:%s" .Values.imageUsername .Values.imagePassword | b64enc) | b64enc }}
{{- end }}