apiVersion: v1
kind: Service
metadata:
  name: {{ template "CustomServiceName.fullname" . }}
  labels:
    app: {{ template "CustomServiceName.name" . }}
    chart: {{ template "CustomServiceName.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "CustomServiceName.name" . }}
    release: {{ .Release.Name }}
