apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsName:
  - xd-aks-ingress.westus2.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
    domains:
    - xd-aks-ingress.westus2.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer