apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: efk
  labels:
    name: elastic-search
    tier: logging
spec:
  clusterIP: None
  selector:
    app: elastic-search
    tier: logging
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: elasticsearch-http
  - protocol: TCP
    port: 9300
    targetPort: 9300
    name: elasticsearch
  - protocol: TCP
    port: 9000
    targetPort: 9000
    name: es-cerebro