apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-search
  namespace: efk
  labels:
    name: elastic-search
    app: elastic-search
    tier: logging
    resource: logging
spec:
  replicas: 1
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elastic-search
      tier: logging
  template:
    metadata:
      labels:
        app: elastic-search
        tier: logging
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      # Service Account
      serviceAccount: elastic-search
      terminationGracePeriodSeconds: 120
      # Containers

      containers:
      - name: cerebro
        image: yannart/cerebro:0.6.4
        ports:
          - containerPort: 9000
            name: es-cerebro
      - name: es
        image: quay.io/pires/docker-elasticsearch-kubernetes:6.1.2
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: efk
        - name: DISCOVERY_SERVICE
          value: elasticsearch
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: HTTP_ENABLE
          value: "true"
        - name: HTTP_CORS_ALLOW_ORIGIN
          # value: "/https?:\/\/localhost(:[0-9]+)?/"
          value: "*"
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: "node.local"
          value: "true"
        - name: "discovery.type"
          value: single-node
        - name: "transport.type"
          value: local
        - name: "discovery.zen.multicast"
          value: "false"
        - name: "discovery.zen.ping.unicast.hosts"
          value: elasticsearch
        volumeMounts:
        - mountPath: /data
          name: esdata
        - mountPath: /etc/elasticsearch/config
          name: config
      # Volumes
      volumes:
      - name: esdata
        persistentVolumeClaim:
          claimName: elastic-search-pvc
      - name: config
        configMap:
          name: elastic-search-config