apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-search-pvc
  namespace: efk
  labels:
    app: elastic-search
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi