apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-search
  namespace: efk
  labels:
    k8s-app: elastic-search
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elastic-search
  labels:
    k8s-app: elastic-search
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: efk
  name: elastic-search
  labels:
    k8s-app: elastic-search
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: elastic-search
  namespace: efk
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elastic-search
  apiGroup: ""