apiVersion: v1
kind: Pod
metadata:
  name: kibana
  namespace: efk
spec:
  containers:
    - name: kibana
      image: blacktop/kibana:6.1.3
      env:
        - name: CLUSTER_NAME
          value: efk
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: SERVER_BASEPATH
          value: /api/v1/namespaces/efk/services/kibana
      ports:
      - containerPort: 5601
        name: ui
        protocol: TCP