apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-web-app
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      containers:
        - image: acrxiaodolidev4.azurecr.io/sa-webappp:master-commitId
          imagePullPolicy: Always
          name: sa-web-app
          env: 
            - name: SA_LOGIC_API_URL
              value: "http://sa-logic"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sa-web-app-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: sa-web-app