envName: dev4
owner: xiaodoli
aksDnsPrefix: hw-aks-xd
subscriptionId: c6f1efb8-906b-437e-99b4-e1f0881ec8d2
aksServicePrincipalAppId: 41ade730-36f4-4e12-a1f6-d05ecc8ec74c
servicePrincipalCertThumbprint: BB55547547C2689A079B11A94914AA87046A57F9
email: xiaodoli@microsoft.com
tenantId: f7215caf-efd9-4bac-89c5-a3cf109a9f18
subscriptionName: RRD MSDN Ultimate
servicePrincipalAppId: 84bb5cf7-232d-44b6-9faa-48372752e48a

helmStorageAccountName: "rrdhelm"
helmBlobContainerName: "helm"